# -*- coding: utf-8 -*-
"""Ubuntu_requests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oG9iv8UngKd4km89_vBX1xVpq0eBg4ie
"""

import os
import requests
from urllib.parse import urlparse
from uuid import uuid4

def fetch_image():
    # 🌐 Community: Connect to the web
    url = input("📸 Enter the image URL: ").strip()

    # 📁 Create directory for sharing
    folder = "Fetched_Images"
    os.makedirs(folder, exist_ok=True)

    try:
        # 🔄 Send HTTP request with User-Agent header
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
        }
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()  # Respect: Handle HTTP errors

        # 🧠 Extract filename or generate one
        parsed_url = urlparse(url)
        filename = os.path.basename(parsed_url.path)
        if not filename or '.' not in filename:
            filename = f"image_{uuid4().hex}.jpg"

        # 💾 Save image in binary mode
        filepath = os.path.join(folder, filename)
        with open(filepath, "wb") as file:
            file.write(response.content)

        print(f"✅ Image saved as '{filename}' in '{folder}'.")

    except requests.exceptions.RequestException as e:
        print(f"❌ Failed to fetch image: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")

# 🚀 Run the script
if __name__ == "__main__":
    fetch_image()